apiVersion: v1
kind: ConfigMap
metadata:
  name: control-config
data:
  conf.yaml: |
    app:
      listen: :8080
      name: "WireFlow"
      env: "development"
      init_admins:
        - username: "admin"
          password: "123456"

    jwt:
      secret: "your-super-secret-key"
      expire_hours: 24

    database:
      driver: "sqlite"
      dsn: "wireflow.db"
