apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: wireflow-controller
    app.kubernetes.io/managed-by: kustomize
  name: wireflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireflow-control
  labels:
    k8s-app: wireflow-control
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: wireflow-control
  template:
    metadata:
      labels:
        k8s-app: wireflow-control
    spec:
      hostAliases:
      - ip: "81.68.109.143"
        hostnames:
          - "signaling.wireflow.run"
      serviceAccountName: wireflow-controller-admin
      containers:
        - name: wireflow-control
          image: controller:latest
          imagePullPolicy: Always
          args:
            - "start"
            - "manager"
            - "--log-level=INFO"
          volumeMounts:
            - mountPath: /app/control.yaml
              name: conf
              subPath: control.yaml
      volumes:
        - name: conf
          configMap:
            name: wireflow-control-config
            items:
              - key: control.yaml
                path: control.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireflow-turn
  labels:
    k8s-app: wireflow-turn
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: wireflow-turn
  template:
    metadata:
      labels:
        k8s-app: wireflow-turn
    spec:
      hostAliases:
        - ip: "81.68.109.143"
          hostnames:
            - "signaling.wireflow.run"
      containers:
        - name: wireflow-turn
          image: controller:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3478
              protocol: UDP
              hostPort: 3478
          args:
            - "start"
            - "turn"
            - "--log-level=verbose"
            - "--public-ip=81.68.109.143"
