apiVersion: apps/v1
kind: Deployment
metadata:
  name: control
  labels:
    k8s-app: wireflow-control
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: wireflow-control
  template:
    metadata:
      labels:
        k8s-app: wireflow-control
    spec:
      hostAliases:
      - ip: "81.68.109.143"
        hostnames:
          - "signaling.wireflow.run"
      serviceAccountName: wireflow-controller-admin
      initContainers:
        - name: wait-for-nats
          image: curlimages/curl:latest
          command:
            - '/bin/sh'
            - '-c'
            - |
              until curl -f http://wireflow-nats-service:8222/varz; do
                echo "Waiting for nats server..."
                sleep 2
              done
      containers:
        - name: wireflow-control
          image: manager:latest
          imagePullPolicy: Always
          args:
            - "start"
            - "manager"
            - "--level=INFO"
          volumeMounts:
            - mountPath: /app/deploy/conf.yaml
              name: conf
              subPath: conf.yaml
      volumes:
        - name: conf
          configMap:
            name: wireflow-control-config
            items:
              - key: conf.yaml
                path: conf.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: turn
  labels:
    k8s-app: turn
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: wireflow-turn
  template:
    metadata:
      labels:
        k8s-app: wireflow-turn
    spec:
      hostAliases:
        - ip: "81.68.109.143"
          hostnames:
            - "signaling.wireflow.run"
      initContainers:
        - name: wait-for-nats
          image: curlimages/curl:latest
          command:
            - '/bin/sh'
            - '-c'
            - |
              until curl -f http://wireflow-nats-service:8222/varz; do
                echo "Waiting for nats server..."
                sleep 2
              done
      containers:
        - name: wireflow-turn
          image: manager:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3478
              protocol: UDP
              hostPort: 3478
          args:
            - "start"
            - "turn"
            - "--level=debug"
            - "--public-ip=81.68.109.143"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wrrper
  labels:
    k8s-app: wireflow-wrrper
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: wireflow-wrrper
  template:
    metadata:
      labels:
        k8s-app: wireflow-wrrper
    spec:
      hostAliases:
        - ip: "81.68.109.143"
          hostnames:
            - "signaling.wireflow.run"
      serviceAccountName: wireflow-controller-admin
      initContainers:
        - name: wait-for-nats
          image: curlimages/curl:latest
          command:
            - '/bin/sh'
            - '-c'
            - |
              until curl -f http://wireflow-nats-service:8222/varz; do
                echo "Waiting for nats server..."
                sleep 2
              done
      containers:
        - name: wireflow-wrrper
          image: manager:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6266
              hostPort: 6266
          args:
            - "start"
            - "wrrper"
            - "--listen=:6266"
            - "--level=INFO"
          volumeMounts:
            - mountPath: /app/control.yaml
              name: conf
              subPath: control.yaml
      volumes:
        - name: conf
          configMap:
            name: wireflow-control-config
            items:
              - key: control.yaml
                path: control.yaml
