resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - service_account.yaml
  - wireflow-role-binding.yaml
  - wireflow-ip-pool.yaml
  - wireflow-web.yaml


images:
  - name: ghcr.io/wireflowio/wireflow-web
    newTag: v0.0.1  # 在这里指定你的特定版本（Tag）