---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-extra-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wireflowcontroller.wireflow.run
  resources:
  - wireflowendpoints
  - wireflowglobalippools
  - wireflowsubnetallocations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wireflowcontroller.wireflow.run
  resources:
  - wireflowendpoints/finalizers
  - wireflowglobalippools/finalizers
  - wireflowsubnetallocations/finalizers
  verbs:
  - update
- apiGroups:
  - wireflowcontroller.wireflow.run
  resources:
  - wireflowglobalippools/status
  verbs:
  - get
  - patch
  - update
