apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: wireflow-controller
    app.kubernetes.io/managed-by: kustomize
  name: manager-extra-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-extra-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
