# This rule is not used by the project wireflow-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over wireflowcontroller.wireflowio.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: wireflow-controller
    app.kubernetes.io/managed-by: kustomize
  name: network-admin-role
rules:
- apiGroups:
  - wireflowcontroller.wireflowio.com
  resources:
  - networks
  verbs:
  - '*'
- apiGroups:
  - wireflowcontroller.wireflowio.com
  resources:
  - networks/status
  verbs:
  - get
