apiVersion: v1
kind: ServiceAccount
metadata:
  name: dex-sa
  namespace: auth
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dex-cluster-role
rules:
  - apiGroups: ["dex.coreos.com"] # Dex 自己的 CRD
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["list", "get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dex-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dex-cluster-role
subjects:
  - kind: ServiceAccount
    name: dex-sa
    namespace: auth