apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireflow-control
  namespace: wireflow
  labels:
    k8s-app: wireflow-control
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: wireflow-control
  template:
    metadata:
      labels:
        k8s-app: wireflow-control
    spec:
      imagePullSecrets:
        - name: ali-registry
      serviceAccountName: wireflow-controller-admin
      containers:
        - name: wireflow-control
          image: registry.cn-hangzhou.aliyuncs.com/wireflow-io/wireflow
          imagePullPolicy: Always
          command: [ "wireflow", "manager" ]
          args:
            - "--log-level=INFO"
          volumeMounts:
            - mountPath: /app/control.yaml
              name: conf
              subPath: control.yaml
      volumes:
        - name: conf
          configMap:
            name: wireflow-control-config
            items:
              - key: control.yaml
                path: control.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: wireflow-control-svc
  namespace: wireflow
spec:
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
      nodePort: 32138
    - protocol: TCP
      name: grpc
      port: 32051
      targetPort: 32051
      nodePort: 32051
  selector:
    k8s-app: wireflow-control
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wireflow-control-config
  namespace: wireflow
data:
  control.yaml: |
    listen: :8080
    database:
      host: 81.68.109.143
      port: 3306
      name: linkany
      user: root
      password: dhvuYUoxnSZMavdJ
    Redis:
      Addr: 81.68.109.143:6379
      Password: dhvuYap

