apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireflow-signaling
  namespace: wireflow
  labels:
    k8s-app: wireflow-signaling
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: wireflow-signaling
  template:
    metadata:
      labels:
        k8s-app: wireflow-signaling
    spec:
      imagePullSecrets:
        - name: ali-registry
      hostAliases:
        - ip: "10.96.98.115"
          hostnames:
            - "console.wireflow.io"
      containers:
        - name: wireflow-signaling
          image: registry.cn-hangzhou.aliyuncs.com/wireflow-io/wireflow:latest
          imagePullPolicy: Always
          command: [ "wireflow", "signaling" ]
          args:
            - "--log-level=verbose"
---
apiVersion: v1
kind: Service
metadata:
  name: wireflow-signaling-svc
  namespace: wireflow
spec:
  ports:
    - protocol: TCP
      port: 32132
      targetPort: 32132
      nodePort: 32132
  selector:
    k8s-app: wireflow-signaling
  type: NodePort
