apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireflow-turn
  namespace: wireflow
  labels:
    k8s-app: wireflow-turn
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: wireflow-turn
  template:
    metadata:
      labels:
        k8s-app: wireflow-turn
    spec:
      imagePullSecrets:
        - name: ali-registry
      hostAliases:
        - ip: "10.96.80.105"
          hostnames:
            - "console.wireflow.io"
      containers:
        - name: wireflow-turn
          image: registry.cn-hangzhou.aliyuncs.com/wireflow-io/wireflow:latest
          imagePullPolicy: Always
          command: [ "wireflow", "turn" ]
---
apiVersion: v1
kind: Service
metadata:
  name: wireflow-turn-svc
  namespace: wireflow
spec:
  ports:
    - protocol: TCP
      port: 32132
      targetPort: 32132
      nodePort: 32132
  selector:
    k8s-app: wireflow-turn
  type: NodePort
