resources:
  - ../../base
  - ../../components/dex
  - ../../components/nats
  - ../../rbac

# 1. 动态修改所有资源的命名空间
namespace: wireflow-system

namePrefix: wireflow-

# 3. 动态替换镜像标签
images:
  - name: wireflow-manager
    newTag: dev

# 4. 如果需要修改环境变量（比如指向不同的 Dex 地址）
patches:
  - target:
      kind: Deployment
      name: wireflow-manager
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "http://dex.auth.svc.cluster.local:5556/dex"