## Append samples of your project ##
resources:
- wireflowcontroller_v1alpha1_node.yaml
- wireflowcontroller_v1alpha1_wireflownetwork.yaml
- wireflowcontroller_v1alpha1_networkpolicy.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
