apiVersion: wireflowcontroller.wireflowio.com/v1alpha1
kind: Network
metadata:
  labels:
    app.kubernetes.io/name: wireflow-controller
    app.kubernetes.io/managed-by: kustomize
  name: network-sample
spec:
  cidr: 10.0.0.0/24