apiVersion: wireflowcontroller.wireflowio.com/v1alpha1
kind: Node
metadata:
  labels:
    app.kubernetes.io/name: wireflow-controller
    app.kubernetes.io/managed-by: kustomize
    app: test
  name: vm-test
spec:
  appId: vm-test
  interfaceName: wireflow-test
  platform: linux
