apiVersion: wireflowcontroller.wireflowio.com/v1alpha1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: wireflow-controller
    app.kubernetes.io/managed-by: kustomize
  name: networkpolicy-sample
spec:
  # TODO(user): Add fields here
