apiVersion: wireflowcontroller.wireflowio.com/v1alpha1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: wireflow-controller
    app.kubernetes.io/managed-by: kustomize
  name: networkpolicy-sample
spec:
  nodeSelector:
    matchLabels:
      app: test
  policyType: "ingress"
  ingressRule:
    - from:
        - peerSelector:
            matchLabels:
              app: test

