apiVersion: wireflowcontroller.wireflow.run/v1alpha1
kind: WireflowNetwork
metadata:
  labels:
    app.kubernetes.io/name: wireflow-controller
    app.kubernetes.io/managed-by: kustomize
  name: network-sample
  namespace: wf-tenant-01
spec:
  name: network-sample