resources:
  - ../../base
  - ../../components/dex
  - ../../components/nats
  - ../../rbac

# 1. 动态修改所有资源的命名空间
namespace: wireflow-system

namePrefix: wireflow-


# 3. 动态替换镜像标签
images:
  - name: wireflow-manager
    newTag: pr-latest

# 4. 如果需要修改环境变量（比如指向不同的 Dex 地址）
patches:
  - patch: patch-resource.yaml
  - patch: patch-env.yaml
  - patch: patch-affinity.yaml