apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireflow-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: NATS_URL
          value: "nats://nats-cluster.prod-infra.svc.cluster.local:4222"
        - name: LOG_LEVEL
          value: "warn"  # 生产环境只看警告和错误
        - name: DEX_ISSUER_URL
          value: "https://auth.wireflow.io/dex" # 生产环境必须用 HTTPS 域名