---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: wireflowenrollmenttokens.wireflowcontroller.wireflow.run
spec:
  group: wireflowcontroller.wireflow.run
  names:
    kind: WireflowEnrollmentToken
    listKind: WireflowEnrollmentTokenList
    plural: wireflowenrollmenttokens
    shortNames:
    - wftoken
    singular: wireflowenrollmenttoken
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: invite to namespace
      jsonPath: .spec.namespace
      name: NAMESPACE
      type: string
    - description: limit to invite
      jsonPath: .spec.usagelimit
      name: USAGELIMIT
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            properties:
              boundPeers:
                items:
                  type: string
                type: array
              expiry:
                format: date-time
                type: string
              namespace:
                type: string
              token:
                type: string
              usageLimit:
                type: integer
            required:
            - expiry
            - namespace
            - token
            - usageLimit
            type: object
          status:
            properties:
              boundPeers:
                items:
                  type: string
                type: array
              isExpired:
                type: boolean
              phase:
                type: string
              token:
                type: string
              usedCount:
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
